<?php

namespace HB\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository {

    private $limitList = 1;

    /**
     * renvoi les articles pour la page accueil
     */
    public function getHomepageArticles($numPage = 0) {

        $offset = $numPage * $this->limitList;
        return $this->findBy(
                        array('published' => true, 'enabled' => true), array('publishDate' => 'desc'), $this->limitList, $offset
        );
    }

    /**
     * renvoi le nb de page 
     */
    public function getHomepageCountPage() {

        $nbArticles = $this->createQueryBuilder('a')
                ->where('a.published=1')
                ->andWhere('a.enabled=1')
                ->select('count(a)')
                ->getQuery()
                ->getSingleScalarResult();
        return (int) ceil($nbArticles/$this->limitList);
    }

}
